# Generated by Django 5.1.4 on 2025-01-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_kyccapturedphoto_project_projectfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyccapturedphoto',
            old_name='photo',
            new_name='photo1',
        ),
        migrations.RemoveField(
            model_name='kyccapturedphoto',
            name='created_at',
        ),
        migrations.AddField(
            model_name='kyccapturedphoto',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_photos/'),
        ),
        migrations.AddField(
            model_name='kyccapturedphoto',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_photos/'),
        ),
        migrations.AddField(
            model_name='kyccapturedphoto',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_photos/'),
        ),
        migrations.AddField(
            model_name='kyccapturedphoto',
            name='photo5',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_photos/'),
        ),
    ]
