# Generated by Django 5.1.4 on 2025-01-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_photo_kyccapturedphoto_photo1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyccapturedphoto',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='kyccapturedphoto',
            name='photo5',
        ),
        migrations.AddField(
            model_name='kyccapturedphoto',
            name='back',
            field=models.ImageField(null=True, upload_to='kyc/documents/'),
        ),
        migrations.AddField(
            model_name='kyccapturedphoto',
            name='front',
            field=models.ImageField(null=True, upload_to='kyc/documents/'),
        ),
        migrations.AlterField(
            model_name='kyccapturedphoto',
            name='photo1',
            field=models.ImageField(null=True, upload_to='kyc/photos/'),
        ),
        migrations.AlterField(
            model_name='kyccapturedphoto',
            name='photo2',
            field=models.ImageField(null=True, upload_to='kyc/photos/'),
        ),
        migrations.AlterField(
            model_name='kyccapturedphoto',
            name='photo3',
            field=models.ImageField(null=True, upload_to='kyc/photos/'),
        ),
    ]
