# Generated by Django 5.1.4 on 2025-01-18 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_kyc'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountName', models.CharField(max_length=100, null=True)),
                ('AccountNo', models.IntegerField(null=True)),
                ('IFSC', models.CharField(max_length=100, null=True)),
                ('BankName', models.CharField(max_length=100, null=True)),
                ('bankid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.account')),
            ],
        ),
        migrations.DeleteModel(
            name='KYC',
        ),
    ]
