# Generated by Django 5.1.4 on 2025-01-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_bankdetails_delete_kyc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='ProjectDis',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='Title',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.AddField(
            model_name='project',
            name='PreviewImage',
            field=models.ImageField(blank=True, null=True, upload_to='preview_images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='PriviewLink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='drive_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='includes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_file',
            field=models.FileField(blank=True, null=True, upload_to='project_files/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=models.FileField(null=True, upload_to='projects/'),
        ),
    ]
