# Generated by Django 5.1.4 on 2025-01-18 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_description_project_projectdis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentId', models.CharField(max_length=100, null=True)),
                ('SaleDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('SaleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
        ),
    ]
