# Generated by Django 5.1.4 on 2025-01-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_bankdetails_linkid'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
