# Generated by Django 5.1.4 on 2025-01-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_project_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ProfileImg',
            field=models.ImageField(null=True, upload_to='ProfileImg'),
        ),
    ]
