# Generated by Django 5.1.4 on 2025-02-05 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_account_profileimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='BuyerAddress',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='BuyerMail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='Payouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaidAmount', models.IntegerField(null=True)),
                ('TransferId', models.CharField(max_length=100, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('PayoutBankID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bankdetails')),
                ('ProductId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sales')),
            ],
        ),
    ]
