# Generated by Django 5.1.4 on 2025-02-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_sales_buyeraddress_sales_buyermail_payouts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payouts',
            name='PaidAmount',
            field=models.BigIntegerField(null=True),
        ),
    ]
