# Generated by Django 5.1.4 on 2025-02-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_payouts_paidamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyccapturedphoto',
            name='back',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='kyccapturedphoto',
            name='front',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='kyccapturedphoto',
            name='photo1',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='kyccapturedphoto',
            name='photo2',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='kyccapturedphoto',
            name='photo3',
            field=models.BinaryField(null=True),
        ),
    ]
