# Generated by Django 5.1.4 on 2025-02-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_kyccapturedphoto_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyccapturedphoto',
            name='back',
            field=models.ImageField(null=True, upload_to='kyc/documents/'),
        ),
        migrations.AlterField(
            model_name='kyccapturedphoto',
            name='front',
            field=models.ImageField(null=True, upload_to='kyc/documents/'),
        ),
        migrations.AlterField(
            model_name='kyccapturedphoto',
            name='photo1',
            field=models.ImageField(null=True, upload_to='kyc/photos/'),
        ),
        migrations.AlterField(
            model_name='kyccapturedphoto',
            name='photo2',
            field=models.ImageField(null=True, upload_to='kyc/photos/'),
        ),
        migrations.AlterField(
            model_name='kyccapturedphoto',
            name='photo3',
            field=models.ImageField(null=True, upload_to='kyc/photos/'),
        ),
    ]
