# Generated by Django 5.1.4 on 2025-02-27 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_kyccapturedphoto_back_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.BigIntegerField(null=True)),
                ('Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Status', models.CharField(choices=[('on_process', 'On Process'), ('done', 'Done')], default='on_process', max_length=20)),
                ('WithdrawID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.account')),
            ],
        ),
    ]
