# Generated by Django 5.1.4 on 2025-02-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_userrevenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.DeleteModel(
            name='UserRevenue',
        ),
    ]
