# Generated by Django 5.1.4 on 2025-03-04 11:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_bankdetails_mobilenumber_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payouts',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
